### ISSUE TITLE
Maybe parametrize tokenizer input max length to rise to Andromeda's magnifcent potential

### ISSUE THREAD

**Issue by JacobFV** [kyegomez/Andromeda#11]
Not sure if you intended to require texts to be tokenized in 8k chunks 

https://github.com/kyegomez/Andromeda/blob/df7f8d5acde934ab73d46909bb3b60cd08c0563d/Andromeda/model.py#L20

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/Andromeda/issues/11">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/Andromeda/issues/11/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/Andromeda/issues/11/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@JacobFV yes i did
