### ISSUE TITLE
Module not found error when running Andromeda.ipynb

### ISSUE THREAD

**Issue by Tylersuard** [kyegomez/Andromeda#5]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting einops
  Downloading einops-0.6.1-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 3.5 MB/s eta 0:00:00
Installing collected packages: einops
Successfully installed einops-0.6.1

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-3-39f0d94718ff>](https://localhost:8080/#) in <cell line: 19>()
     17 from torch.serialization import load
     18 import torch
---> 19 from x_transformers import TransformerWrapper, Decoder, AutoregressiveWrapper
     20 
     21 #training

ModuleNotFoundError: No module named 'x_transformers'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by kyegomez** [comment]
@Tylersuard Hey Tyler, I never saw this! Please excuse me.

That script is old, what is your objective with Andromeda? To Train it?
